const products = [
  {
    id: 1,
    name: "Кольцо «Сияние»",
    category: "Кольца",
    metal: "Серебро",
    material: "Серебро 925°, фианит",
    price: 12990,
    image: "/img/photo-1605100804763-247f67b3557e.jpg",
    description: "Изящное кольцо с крупным фианитом в классической закрепке из 6 лап. Подходит для повседневной носки и особых случаев.",
    tags: ["recommended"],
  },
  {
    id: 2,
    name: "Подвеска «Луна»",
    category: "Подвески",
    metal: "Золото",
    material: "Золото 585°, бриллиант",
    price: 24990,
    image: "/img/photo-1611591437281-460bfbe1220a.jpg",
    description: "Нежная подвеска на тонкой золотой цепочке с бриллиантом в форме капли. Символ женственности и лёгкости.",
    tags: ["recommended"],
  },
  {
    id: 3,
    name: "Серьги «Вечность»",
    category: "Серьги",
    metal: "Серебро",
    material: "Серебро 925°, фианиты",
    price: 16990,
    image: "/img/photo-1535632066927-ab7c9ab60908.jpg",
    description: "Серьги-кольца с дорожкой фианитов по всей окружности. Ловят свет под любым углом.",
    tags: ["recommended"],
  },
  {
    id: 4,
    name: "Кольцо «Минимал»",
    category: "Кольца",
    metal: "Серебро",
    material: "Серебро 925°, фианит",
    price: 9990,
    image: "/img/photo-1599643478518-a784e5dc4c8f.jpg",
    description: "Тонкое кольцо лаконичной формы с одним небольшим фианитом. Отлично сочетается с другими украшениями.",
    tags: ["bestseller"],
  },
  {
    id: 5,
    name: "Браслет «Классика»",
    category: "Браслеты",
    metal: "Золото",
    material: "Золото 585°, фианиты",
    price: 18990,
    image: "/img/photo-1620656798579-1984d9e87df7.jpg",
    description: "Гибкий золотой браслет с рядом фианитов по всей длине. Регулируемая застёжка подходит на любое запястье.",
    tags: ["bestseller"],
  },
  {
    id: 6,
    name: "Серьги «Звезда»",
    category: "Серьги",
    metal: "Серебро",
    material: "Серебро 925°, фианит",
    price: 11990,
    image: "/img/photo-1535632066927-ab7c9ab60908.jpg",
    description: "Серьги-пуссеты в форме звезды с одним фианитом в центре. Небольшой яркий акцент на каждый день.",
    tags: ["bestseller"],
  },
  {
    id: 7,
    name: "Колье «Сердце»",
    category: "Подвески",
    metal: "Золото",
    material: "Золото 585°, бриллиант",
    price: 22990,
    image: "/img/photo-1611591437281-460bfbe1220a.jpg",
    description: "Колье с кулоном в форме сердца и бриллиантом в центре. Романтичный подарок для особенного человека.",
    tags: ["bestseller"],
  },
  {
    id: 8,
    name: "Кольцо «Галактика»",
    category: "Кольца",
    metal: "Серебро",
    material: "Серебро 925°, топаз",
    price: 14990,
    image: "/img/photo-1605100804763-247f67b3557e.jpg",
    description: "Кольцо с крупным топазом глубокого синего оттенка. Смелый выбор для тех, кто любит выделяться.",
    tags: ["bestseller"],
  },
  {
    id: 9,
    name: "Кольцо «Аврора»",
    category: "Кольца",
    metal: "Золото",
    material: "Золото 585°, фианит",
    price: 15990,
    image: "/img/photo-1599643478518-a784e5dc4c8f.jpg",
    description: "Золотое кольцо с фианитом, огранка которого создаёт эффект переливающегося света — как северное сияние.",
    tags: ["recommended"],
  },
  {
    id: 10,
    name: "Браслет «Нежность»",
    category: "Браслеты",
    metal: "Серебро",
    material: "Серебро 925°, фианиты",
    price: 13990,
    image: "/img/photo-1620656798579-1984d9e87df7.jpg",
    description: "Тонкий серебряный браслет-цепочка с мелкими фианитами. Можно носить в многослойных сочетаниях.",
    tags: ["recommended"],
  },
  {
    id: 11,
    name: "Кольцо «Мечта»",
    category: "Кольца",
    metal: "Серебро",
    material: "Серебро 925°, фианит",
    price: 10990,
    image: "/img/photo-1599643478518-a784e5dc4c8f.jpg",
    description: "Воздушное кольцо тонкой работы с одним фианитом. Легко комбинируется в наборе с другими кольцами.",
    tags: ["bestseller"],
  },
  {
    id: 12,
    name: "Подвеска «Река»",
    category: "Подвески",
    metal: "Золото",
    material: "Золото 585°, бриллиант",
    price: 21990,
    image: "/img/photo-1611591437281-460bfbe1220a.jpg",
    description: "Подвеска плавной вытянутой формы с бриллиантом, напоминающая изгиб реки. На цепочке длиной 45 см.",
    tags: ["bestseller"],
  },
  {
    id: 13,
    name: "Серьги «Роса»",
    category: "Серьги",
    metal: "Серебро",
    material: "Серебро 925°, фианиты",
    price: 12990,
    image: "/img/photo-1535632066927-ab7c9ab60908.jpg",
    description: "Серьги-гвоздики с фианитами, напоминающими капли утренней росы. Универсальны для любого образа.",
    tags: ["bestseller"],
  },
  {
    id: 14,
    name: "Браслет «Гармония»",
    category: "Браслеты",
    metal: "Золото",
    material: "Золото 585°, фианит",
    price: 19990,
    image: "/img/photo-1620656798579-1984d9e87df7.jpg",
    description: "Плотный золотой браслет с фианитом в центральном звене. Уверенный акцент на запястье.",
    tags: ["bestseller"],
  },
];

export default defineEventHandler((event) => {
  const { tag } = getQuery(event);

  if (typeof tag === "string") {
    return products.filter((product) => product.tags.includes(tag));
  }

  return products;
});
